### ISSUE TITLE
Saturation stuff doesn't work

### ISSUE THREAD

**Issue by mastamike911** [software-2/nanoleaf#1]
It looks like the script is referring to saturation within the state as "saturation" but in my state string it is actually referred to as "sat". This causes all the saturation stuff in aurora.py to not work.

My state:
 'state': {'on': {'value': True}, 'brightness': {'value': 45, 'max': 100, 'min': 0}, 'hue': {'value': 290, 'max': 360,
 'min': 0}, 'sat': {'value': 74, 'max': 100, 'min': 0}, 'ct': {'value': 4000, 'max': 100, 'min': 0}, 'colorMode': 'hs'}

**Comment by software-2** [comment]
Whoops! Thanks for catching that! Need to write some unit tests!
This should be fixed in 0.3.1
