### ISSUE TITLE
Brightness increment doesn't work

### ISSUE THREAD

**Issue by Lolincolc** [software-2/nanoleaf#5]
Hi everyone !

I'm using this python module in my project. Everything is working find but i'm getting a problem when trying to set the brightness by increment.
Here is my code : 
```
effect_data = {
    "brightness": {
        "increment": -10
    }
}

my_aurora.effect_set_raw(effect_data)
```

I'm getting this error : 
`Error 422: Unprocessible Entity`

Am I doing something wrong ?

Thanks in advance for your answer !

**Comment by software-2** [comment]
You don't need to specify any JSON when using this module to set brightness. The effect stuff is for more complicated things.

`my_aurora.brightness_lower(10)`

**Comment by Lolincolc** [comment]
Thank you ! I don't know why I didn't try that, now I'm seeing this in the documentation and this is working perfectly !
Thanks again for this module that is really usefull.
